 {{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
   {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-1
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
   {{- if eq .Values.favorite.drink "coffee" }}
  sugar: "true"
   {{- end }}
  mobile: "900"
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-configmap-2
# data:
#   myvalue: "Hello World"
#    {{- with .Values.favorite }}
#   drink: {{ .drink | default "tea" | quote }}
#   food: {{ .food | upper | quote }}
#   release: {{ $.Release.Name }}
#    {{- end }}
#---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-configmap-3
# data:
#   myvalue: "Hello World"
#    {{- with .Values.favorite }}
#   drink: {{ .drink | default "tea" | quote }}
#   food: {{ .food | upper | quote }}
#    {{- end }}
#   toppings: |-
#     {{- range .Values.pizzaToppings }}
#     - {{ . | title | quote }}
#     {{- end }}
#
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#   name: {{ .Release.Name }}-configmap-4
#data:
#   myvalue: "Hello World"
#   toppings: |-
#     {{- range $key, $value := .Values.favorite }}
#     {{ $key | title | quote }}={{ $value }}
#     {{- end }}
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#   name: {{ .Release.Name }}-configmap-5
#data:
#   myvalue: "Hello World"
#    {{- $relname := .Release.Name -}} ## We are declaring a variable here
#    {{- with .Values.favorite }}
#   drink: {{ .drink | default "tea" | quote }}
#   food: {{ .food | upper | quote }}
#   release: {{ $relname }}
#    {{- end }}

